/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { CommunitySBT } from "./contracts/CommunitySBT";
export { CommunitySBT__factory } from "./factories/contracts/CommunitySBT__factory";
