/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAaveV3LendingPool,
  IAaveV3LendingPoolInterface,
} from "../IAaveV3LendingPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20Minimal",
        name: "asset",
        type: "address",
      },
    ],
    name: "getReserveNormalizedIncome",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAaveV3LendingPool__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveV3LendingPoolInterface {
    return new utils.Interface(_abi) as IAaveV3LendingPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveV3LendingPool {
    return new Contract(address, _abi, signerOrProvider) as IAaveV3LendingPool;
  }
}
